### ISSUE TITLE
طرح مربوط به عکس زیر رو اجرا کن

### ISSUE THREAD

**Issue by aminghe** [abasfn/abas3#1]
طرح رو اجرا کردی باید به صورت انلاین به من نشون بده که چیکار کردی

<img width="1209" alt="Screen Shot 2019-04-06 at 19 30 49" src="https://user-images.githubusercontent.com/16360624/55671194-9dfc1380-58a2-11e9-8397-41f39f10fb65.png">

refrence: http://spiralpixelthemes.co.uk/flatinew/flati/index.html

**Comment by aminghe** [comment]
عباس وقتی کارت تموم میشه اینجا بهم بگو که کارت تموم میشه و کامیتت رو واسم بنویس

الان کاری که تو بهم دادی اینه

<img width="1680" alt="Screen Shot 2019-04-08 at 19 56 36" src="https://user-images.githubusercontent.com/16360624/55736412-7d65c200-5a38-11e9-9e78-14ba266664fe.png">

نمونه سایت رو هم بهم دادم

۱- رنگ کادرهای تو عکسا که رنگش یکی نیست
۲- کادر اندازش رو ۱۲۰۰ در نظر بگیر و وسط چین باشه عین نمونه که بهت دادم
۳- فلش های بالای عکس ها کو؟
۴- نوشته ها خیلی نامرتب هستش
۵- متن داخل اون دکمه نیست
۶- عناصر سرجای خودشون نیستن

عین طرح دربیار

**Comment by abasfn** [comment]
امین این عناصر تو کامپیوتر من جاش فرق میکنه اینجا اصلا جاش عوض شده

**Comment by abasfn** [comment]
اصلا این نوشته ها همه یه طرف بود الان جاش عوض شده

**Comment by aminghe** [comment]
<div dir="rtl">
اشتباهیی طراحی کردی
یه فیلم تو تلگرام واست فرستادم
اون رو با دقت نگاه کن
</div>
@abasfn
