### ISSUE TITLE
تمرین سوم

### ISSUE THREAD

**Issue by aminghe** [abasfn/abas3#3]
<div dir="rtl">

اجرای طرح

<img width="1666" alt="Screen Shot 2019-04-12 at 14 04 40" src="https://user-images.githubusercontent.com/16360624/56027895-3293c500-5d2c-11e9-98e5-48e5102c8763.png">

</div>

refrence : https://bootstrap-themes.github.io/application/?ver=2

**Comment by abasfn** [comment]
امین چی شد

**Comment by abasfn** [comment]
امین من پروزه موبایلشو زدم فقط اگه وقت داشتی بهم بگو از شما سوال دارم

**Comment by abasfn** [comment]
امین بعد روی گیت هاب  پوشم کردم اگه خواستی ببین

**Comment by aminghe** [comment]
فردا بعد شرکت سوال هر چی داری بپرس جواب میدم.

**Comment by aminghe** [comment]
@abasfn 
فیلم واست فرستادم رو نلگرام.

اونارو درست کن کامیت کن.

**Comment by abasfn** [comment]
امین من کامیت کردم فقط یه چنتا مشکل دیگه دارم اونارو درست کردم
