### ISSUE TITLE
یه پروژه با استفاده از sass یا less

### ISSUE THREAD

**Issue by aminghe** [abasfn/abas3#5]
<div dir="rtl">

یه پروژه باید بزنی - دلخواهی

با استفاده از sass یا less

خودتون باید جستجو کنید . بر اساس آموزش هایی که هست راه اندازیش کنید.

از اینم میتونی استفاده کنی

https://roocket.ir/series/learning-sass/episode/1

@abasfn 
</div>

**Comment by aminghe** [comment]
سه شنبه پروژه تو قالب پوشه github4 تحویل گرفته میشه.

عیاس الان پوشه ۴ ات پره - اگه بیای ۵ درست کنی من به هیچ عنوان نگا نمیکنم.

@abasfn

**Comment by aminghe** [comment]
از رو تنظیمات هم برنچش رو خصوصی بکن
اگه بلد نبودی سرچ کن.
@abasfn

**Comment by abasfn** [comment]
امین اینو تو تلگرام پیام میدادی من همین الان دیدم

**Comment by abasfn** [comment]
> 
> 
> سه شنبه پروژه تو قالب پوشه github4 تحویل گرفته میشه.
> 
> عیاس الان پوشه ۴ ات پره - اگه بیای ۵ درست کنی من به هیچ عنوان نگا نمیکنم.
> 
> @abasfn

یعنی چی پره

**Comment by aminghe** [comment]
@abasfn 
یعنی اینکه من تمرین چهارم ندادم شما پوشه ای به عنوان تمرین چهارم داری.

موردی اولم اینکه من فقط اینجا بهت میگم جای دیگه خبرت نمیکنم که پروژه داری

**Comment by abasfn** [comment]
امین رو همین پروزه ای که زدم میتونم بزنم

**Comment by abasfn** [comment]
https://github.com/abasfn/abas3/commit/b4910ef0234ce36b6c6db64fc7ee198bd83260f1

**Comment by abasfn** [comment]
امین تموم کردم ببین

**Comment by aminghe** [comment]
حله چک کردم.
